// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfxcxoyvrwhrdaktxeuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmeGN4b3l2cndocmRha3R4ZXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTQ5ODEsImV4cCI6MjA2MTkzMDk4MX0.JvDiBvdPFeImwVRKhy6RMqA2Ex34HWbpUo_du02PCC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);